/**
 * name : message-constants/common.js
 * author : Akash Shah
 * Date : 09-Dec-2019
 * Description : All common messages.
 */


module.exports = {
  "SUCCESS" : "Success.",
  "FAILED" : "Failed.",
  "OK" : "OK",
  "BODH_DIAL_CODE_LIVE_STATUS" : "Live",
  "USER_PROFILE_PENDING_VERIFICATION_STATUS":"pendingVerification",
  "USER_PROFILE_NOT_VERIFIED_STATUS":"notVerified",
  "USER_PROFILE_VERIFIED_STATUS":"verified",
  "USER_PROFILE_PENDING_STATUS" : "pendingVerification",
  "USER_PROFILE_FORM_NAME":"userProfileForm",
  "STATE_ENTITY_TYPE":"state",
  "ALL_APP_VERSION" : "allAppVersion",
  "ACTIVE" : "active",
  "IN_ACTIVE" : "inactive",
  "BODH_DIAL_CODE_LIVE_STATUS" : "Live",
  "GOA_STATE" : "Goa",
  "UNNATI_APP_NAME" : "unnati",
  "PROFILE_UPDATE_NOTIFICATION_MESSAGE":"Please update your details.Help us make your experience better.",
  "PROFILE_UPDATE_TITLE" : "Confirm your details.",
  "GET_METHOD" : "GET",
  "POST_METHOD" : "POST",
  "AWS_SERVICE": "AWS",
  "GOOGLE_CLOUD_SERVICE": "GC",
  "AZURE_SERVICE": "AZURE",
  "NO_OF_MINUTES" : 30,
  "NO_OF_EXPIRY_TIME" : 60,
  "BODH_CONTENT_TYPE" : "Resource",
  "BODH_MIME_TYPE" : "application/vnd.ekstep.html-archive",
  "FORM_DATA_CONTENT_TYPE" : "application/x-www-form-urlencoded",
  "ORGANISATION_LIMIT" : 1000,
  "ORGANISATIONS_OFFSET" : 0,
  "ORGANISATION_LISTS" : "organisation-lists",
  "UPLOAD_FOLDER_PATH" : "/public/upload",
  "APPS_UPLOAD_FILE_PATH" : "static/apps/",
  "VERSION_1" : "v1",
  "VERSION_2" : "v2",
  "ASSESSMENT" : "assessment",
  "INSTITUTIONAL" : "institutional",
  "USER_ORGANISATIONS_FETCHED" : "User organisations fetched successfully",
  "LEARNING_RESOURCE_FILTER_FORM_NAME":"learning-resource-filters",
  "PROJECT" : "project",
  "OBSERVATION" : "observation",
  "IMPROVEMENT_PROJECT" : "improvementProject",
  "SURVEY" : "survey",
  "TARGETED_SOLUTION_TEXT" : "View and participate in educational programs active in your location and designed for your role.",
  "ALL_ROLES" : "all",
  "ASSIGN_TO_ME" : "assignedToMe",
  "CREATED_BY_ME" : "createdByMe",
  "DEFAULT_PAGE_SIZE" : 100,
  "DEFAULT_PAGE_NO" : 1,
  "DHITI" : "dhiti"
};
